name: dockflow-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pytest
  - ipython
  - rdkit
  - meeko 
  - pandas
  - numpy
  - mdtraj
  - mdanalysis
  # - posebusters from pip
  - pip
